import { DMMF } from '@prisma/generator-helper';
import fs from 'fs/promises';
import path from 'path';

const header = `// This file was generated by a custom prisma generator, do not edit manually.\n`;

export default async function GenerateModelNames(options: DMMF.Datamodel) {
  const models = options.models
  const union = models.map((m) => `"${m.name}"`).join(" | ");

  const content = `
    ${header}
    export type ModelName = ${union};
  `.trim();



  const target = path.join( "./node_modules/prisma-x-zod/dist/helpers/model-names.ts");

  await fs.writeFile(target, content, { encoding: 'utf-8' });

  console.log(`\n✨ Done`);
}