import fs from "fs/promises";
import path from "path";
import type { DMMF } from "@prisma/generator-helper";

const header = `// This file was generated by a custom Prisma generator.
// Do NOT edit manually.\n\n`;

export default async function TypeGen(datamodel: DMMF.Datamodel) {
  const models = datamodel.models;

  let allTypes = header;

  for (const model of models) {
    const fields = model.fields;

    const typeLines = fields
      .map((f) => {
        const tsType = prismaScalarToTs(f.type);
        return `  ${f.name}: ${tsType};`;
      })
      .join("\n");

    allTypes += `export type ${model.name} = {\n${typeLines}\n};\n\n`;
  }

  allTypes += "export interface PrismaModels {\n";
  for (const model of models) {
    allTypes += `  ${model.name}: ${model.name};\n`;
  }
  allTypes += "}\n";

  const outPath = path.join(
    "./node_modules/prisma-x-zod/dist/helpers/",
    "types.ts"
  );

  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, allTypes, "utf8");

  console.log();
}

function prismaScalarToTs(type: any) {
  switch (type) {
    case "String":
      return "string";
    case "Int":
      return "number";
    case "Float":
      return "number";
    case "Boolean":
      return "boolean";
    case "DateTime":
      return "Date";
    case "Json":
      return "any";
    case "BigInt":
      return "bigint";
    default:
      return "unknown";
  }
}
