import { GeneratorOptions } from '@prisma/generator-helper';
import { mkdirSync } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';

const header = `// This file was generated by a custom prisma generator, do not edit manually.\n`;

export default async function onGenerate(options: GeneratorOptions) {
  const models = options.dmmf.datamodel.models;
  const union = models.map((m) => `"${m.name}"`).join(" | ");

  const content = `
    ${header}
    export type ModelName = ${union};
  `.trim();

  const outputDir = options.generator.output?.value;

  if (!outputDir) {
    throw new Error("❌ No output directory provided in generator block.");
  }

  mkdirSync(outputDir, { recursive: true });

  const target = path.join(outputDir, "model-names.ts");

  await fs.writeFile(target, content);

  console.log(`\n✨ Generated model names at: ${target}\n`);
}